/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class ElevatorSimulator {
    public String getStartupMessage() {
        return "Starting up simulator";
    }

    public static void main(String[] args) {
        System.out.println(new ElevatorSimulator().getStartupMessage());
    }
}
