/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ElevatorSimulatorTest {
    @Test public void testAppHasAStartupMessage() {
        ElevatorSimulator classUnderTest = new ElevatorSimulator();
        assertNotNull("app should have a startup message", classUnderTest.getStartupMessage());
    }
}
