/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ElevatorSimulatorTest {
    @Test public void testAppHasAStartupMessage() {
        ElevatorSimulator classUnderTest = new ElevatorSimulator();
        assertNotNull("app should have a startup message", classUnderTest.getStartupMessage());
    }

    @Test
    public void testNoArgDetaultFloorsAndElevators() {
        ElevatorSimulator classUnderTest = new ElevatorSimulator();
        assertEquals("simulator should have 1 elevator", 1, classUnderTest.getElevators().size());
    }

    @Test
    public void testArgsShouldMatchFloorsAndElevators() {
        int floors = 10;
        int elevators = 2;
        ElevatorSimulator classUnderTest = new ElevatorSimulator(floors, elevators);
        assertEquals("simulator should have correct nuber of elevators", elevators, classUnderTest.getElevators().size());
    }
}
